### ISSUE TITLE
Tag List filtering does not work on PHP 7 with list option

### ISSUE THREAD

**Issue by Caspercode444** [lisps/tagfilter#11]
The tag filtering works fine if i don't use the `list or table or simplelist` flag. 
Here is the code that works
`{{tagfilter>:?Tag=.*}}
`
On adding simplelist flag, It does not filter pages according to the selected tag.  
`{{tagfilter>:?Tag=.*&simplelist}}`
I have checked /var/log/apache2/error.log and its empty.

PHP Version => 7.2.10-0ubuntu0.18.04.1

**Comment by peterfromearth** [comment]
Which versions of tag, pagelist & tagfilter are you using?

**Comment by Caspercode444** [comment]
Looking at individual plugin folders, the versions are
tag: 2018-04-22a "Greebo"
pagelist date:   2017-08-24
tag-filter date:   2018-10-04

**Comment by 0-1** [comment]
First time I try to use this plugin, but it seems I encounter this problem. For now I haven't been able to make it work at all.

In Dokuwiki page:
`{{tagfilter>Genre=genre:.*}}`

In web server error.log:
`2018/12/16 18:00:55 [error] 11424#11424: *6 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_case() in /home/fab/www/mysite.com/lib/plugins/tagfilter/helper.php:100
Stack trace:
#0 /home/fab/www/mysite.com/lib/plugins/tagfilter/syntax/filter.php(251): helper_plugin_tagfilter->getTagLabel('genre:arcade')
#1 /home/fab/www/mysite.com/inc/parser/renderer.php(111): syntax_plugin_tagfilter_filter->render('xhtml', Object(Doku_Renderer_xhtml), Array)
#2 /home/fab/www/mysite.com/inc/parserutils.php(654): Doku_Renderer->plugin('tagfilter_filte...', Array, 5, '{{tagfilter>" while reading upstream, client: 78.248.143.138, server: mysite.com, request: "GET /jeux HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "mysite.com", referrer: "https://mysite.com/jeux"
2018/12/16 18:00:55 [error] 11424#11424: *6 FastCGI sent in stderr: "Gen...')
#3 /home/fab/www/mysite.com/inc/parserutils.php(130): p_render('xhtml', Array, NULL)
#4 /home/fab/www/mysite.com/inc/parserutils.php(83): p_cached_output('/home/fab/www/j...', 'xhtml', 'jeux')
#5 /home/fab/www/mysite.com/inc/html.php(293): p_wiki_xhtml('jeux', 0, true, '')
#6 /home/fab/www/mysite.com/inc/Action/Show.php(33): html_show()
#7 /home/fab/www" while reading upstream, client: 78.248.143.138, server: mysite.com, request: "GET /jeux HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "mysite.com", referrer: "https://mysite.com/jeux"`

**Comment by peterfromearth** [comment]
You are missing the mbstring extension

**Comment by 0-1** [comment]
That's right, I just installed it and it looks allright now ;) Sorry for the noise.

**Comment by peterfromearth** [comment]
please try 2020-02-21 again
