### ISSUE TITLE
TagFilter not showing any results

### ISSUE THREAD

**Issue by vogtadi** [lisps/tagfilter#12]
versions are
dokuwiki: 2018-04-22b "Greebo"
tag date: 2017-08-24
pagelist date: 2017-08-24
tag-filter date: 2018-10-04
php: 7.0.33-0+deb9u3

**with even the simplest syntax, e.g. `{{tagfilter>:?Tag=.*}}`, no results are displayed.**

Looking into the javascript-console, the error seems to be line 71 of script.js (tagfilter_submit, loop through select boxes) where the "tags" variable is undefined and hence the code breaks. The variable "tags" is assigned in line 32 of script.js (4th statement in tagfilter_submit). While the page clearly has an element with id "#tagdd_"+x, the data function seems to retrieve an undefined tags object from this element.

Not sure, when the code broke. I noticed it a few weeks back, but only now found the time to start investigating it at bit.

**Comment by vogtadi** [comment]
I tried to gather additional information by installing a plain vanilla dokuwiki installation.

It **works** with dokuwiki and the three plugins out of the box with **default** settings. If I strip down my installation to exactly the same plugins (some built in and the three required), the problem still exists. Also no setting could be identified, that makes a difference either. Neither does an index-rebuild help.

After a lengthy search, I noticed a php_errors.log inside ./lib/exe (location and whether or not this file is generated might depend on your PHP.ini settings). That log file contained the following two errors:


**it looks like on my installation, there are two additional files, syntax.php and ajax.php, from an older version**. These files have been renamed / broken up, but the upgrade of the plugin seems to have left these files around. Even a "re-install" plugin from the UI does not resolve this. However it's possible to **REMOVE and Add the plugin** to resolve the issue.

### Conclusion
I am **not** sure, whether the plugin can specify **files to delete on upgrade**. If so, it would make sense to declare the two files to be outdated.
- syntax.php
- ajax.php

**Comment by peterfromearth** [comment]
thanks for your investigation. There is indeed a file for deleted files https://www.dokuwiki.org/devel:deleted.files

**Comment by vogtadi** [comment]
thanks for the quick update!

Since I still had things lying around and could test it out easily, I can **confirm**, that this fixes the issue (removes the files and results in a working plugin).
