### ISSUE TITLE
Fatal error - deprecated PHP syntax in syntax.php on line 74

### ISSUE THREAD

**Issue by SabineSW** [lisps/tagfilter#21]
Hi,

after an upgrade of PHP from 8.0.9 to 8.0.11 dokuwiki (hogfahter) no longer shows proper pages.

In /var/log/apache2/error.log:
Got error 'PHP message: PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /data/httpd/wiki/lib/plugins/tagfilter/helper/syntax.php on line 74'

Please add the parentheses needed.

Thank you!

**Comment by peterfromearth** [comment]
can you try version 2021-10-19?
