### ISSUE TITLE
TagFilter PHP8.1 Upgrade critical Error

### ISSUE THREAD

**Issue by thisislukasbenz** [lisps/tagfilter#23]
after upgrading to php8.2 wholw Wik works just not the TagFilter plugin i get following error:

2022-08-12 10:38:05
Error: Call to undefined function mb_convert_case()
/var/www/dokuwiki/lib/plugins/tagfilter/helper.php(92)
#0 /var/www/dokuwiki/lib/plugins/tagfilter/syntax/filter.php(251): helper_plugin_tagfilter->getTagLabel()
#1 /var/www/dokuwiki/inc/parser/renderer.php(117): syntax_plugin_tagfilter_filter->render()
#2 /var/www/dokuwiki/inc/parserutils.php(682): Doku_Renderer->plugin()
#3 /var/www/dokuwiki/inc/parserutils.php(149): p_render()
#4 /var/www/dokuwiki/inc/parserutils.php(89): p_cached_output()
#5 /var/www/dokuwiki/inc/Ui/PageView.php(68): p_wiki_xhtml()
#6 /var/www/dokuwiki/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
#7 /var/www/dokuwiki/inc/template.php(100): dokuwiki\Action\Show->tplContent()
#8 [internal function]: tpl_content_core()
#9 /var/www/dokuwiki/inc/Extension/Event.php(133): call_user_func_array()
#10 /var/www/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
#11 /var/www/dokuwiki/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
#12 /var/www/dokuwiki/lib/tpl/bootstrap3/main.php(117): tpl_content()
#13 /var/www/dokuwiki/inc/actions.php(27): include('/var/www/dokuwi...')
#14 /var/www/dokuwiki/doku.php(126): act_dispatch()
#15 {main}

**Comment by Klap-in** [comment]
You are missing the mbstring extension, please check if it is also installed for the php version you are using.

**Comment by thisislukasbenz** [comment]
> You are missing the mbstring extension, please check if it is also installed for the php version you are using.

ah my bad dude thank you a ton this whole Wiki Community and around it is amazing! I Will try it with that extension on php8.1 thanks!

**Comment by thisislukasbenz** [comment]
> You are missing the mbstring extension, please check if it is also installed for the php version you are using.

tried this but still i get following error on the home screen

TypeError: filemtime(): Argument #1 ($filename) must be of type string, array given
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the tagfilter plugin.

More info has been written to the DokuWiki error log.

**Comment by Klap-in** [comment]
The DokuWiki error log can be find here: https://www.dokuwiki.org/plugin:logviewer

Could you share the longer error message from the log?

**Comment by thisislukasbenz** [comment]
2022-08-16 08:04:01
TypeError: filemtime(): Argument #1 ($filename) must be of type string, array given
/var/www/dokuwiki/inc/Cache/Cache.php(129)
#0 /var/www/dokuwiki/inc/Cache/Cache.php(129): filemtime()
#1 /var/www/dokuwiki/inc/Cache/Cache.php(91): dokuwiki\Cache\Cache->makeDefaultCacheDecision()
#2 /var/www/dokuwiki/lib/plugins/tagfilter/syntax/filter.php(146): dokuwiki\Cache\Cache->useCache()
#3 /var/www/dokuwiki/inc/parser/renderer.php(117): syntax_plugin_tagfilter_filter->render()
#4 /var/www/dokuwiki/inc/parserutils.php(682): Doku_Renderer->plugin()
#5 /var/www/dokuwiki/inc/parserutils.php(149): p_render()
#6 /var/www/dokuwiki/inc/parserutils.php(89): p_cached_output()
#7 /var/www/dokuwiki/inc/Ui/PageView.php(68): p_wiki_xhtml()
#8 /var/www/dokuwiki/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
#9 /var/www/dokuwiki/inc/template.php(100): dokuwiki\Action\Show->tplContent()
#10 [internal function]: tpl_content_core()
#11 /var/www/dokuwiki/inc/Extension/Event.php(133): call_user_func_array()
#12 /var/www/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
#13 /var/www/dokuwiki/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
#14 /var/www/dokuwiki/lib/tpl/bootstrap3/main.php(117): tpl_content()
#15 /var/www/dokuwiki/inc/actions.php(27): include('...')
#16 /var/www/dokuwiki/doku.php(126): act_dispatch()
#17 {main}

Here it is hope it helps.

> The DokuWiki error log can be find here: https://www.dokuwiki.org/plugin:logviewer
> 
> Could you share the longer error message from the log?

**Comment by Klap-in** [comment]
In a coming pull request I will propose the following change for:
> 2022-08-12 10:38:05
> Error: Call to undefined function mb_convert_case()
> /var/www/dokuwiki/lib/plugins/tagfilter/helper.php(92)

```diff
- 		return mb_convert_case(str_replace('_',' ',trim($label,':')), MB_CASE_TITLE, "UTF-8");
+		return dokuwiki\Utf8\PhpString;::ucwords(str_replace('_',' ',trim($label,':')));
```

And for this I expect this will solve it. But I haven't reproduce it yet. When do you get it? And does this fix it?
>TypeError: filemtime(): Argument https://github.com/lisps/tagfilter/issues/1 ($filename) must be of type string, array given
/var/www/dokuwiki/inc/Cache/Cache.php(129)

```diff
- 			$depends = array('files'=>array(
- 				$INFO['filepath'],
- 				DOKU_CONF . '/acl.auth.php',
- 				getConfigFiles('main'),		
- 			));
+			$depends = array('files'=>array(
+				$INFO['filepath'],
+				DOKU_CONF . '/acl.auth.php',
+			));
+ 			$depends['files'] = array_merge($depends['files'], getConfigFiles('main'));
```

**Comment by thisislukasbenz** [comment]
> In a coming pull request I will propose the following changes for:
> 
> > 2022-08-12 10:38:05
> > Error: Call to undefined function mb_convert_case()
> > /var/www/dokuwiki/lib/plugins/tagfilter/helper.php(92)
> 
> ```diff
> - 		return mb_convert_case(str_replace('_',' ',trim($label,':')), MB_CASE_TITLE, "UTF-8");
> +		return dokuwiki\Utf8\PhpString;::ucwords(str_replace('_',' ',trim($label,':')));
> ```
> 
>  > TypeError: filemtime(): Argument #1 ($filename) must be of type string, array given
> > /var/www/dokuwiki/inc/Cache/Cache.php(129)
> 
> And for this I expect this will solve it. But I haven't reproduce it yet. When do you get it? And does this fix it?
> 
> ```diff
> - 			$depends = array('files'=>array(
> - 				$INFO['filepath'],
> - 				DOKU_CONF . '/acl.auth.php',
> - 				getConfigFiles('main'),		
> - 			));
> +			$depends = array('files'=>array(
> +				$INFO['filepath'],
> +				DOKU_CONF . '/acl.auth.php',
> +			));
> + 			$depends['files'] = array_merge($depends['files'], getConfigFiles('main'));
> ```

That’s really weird the first line was no problem i replaced it with the new One. But all the Lines on the Cache.php not even existed in that File in the already in use Wiki and the Testing Wiki. 
Should I just add them to the bottom of the php file ?

**Comment by thisislukasbenz** [comment]
Okay so simply adding that Text to the bottom of the Cache.php gives me only more Errors…

**Comment by Klap-in** [comment]
Sorry my instructions were incomplete.
The second change should be applied to another file. Please do not put it to the end of the first one.

the old version is here, please make in that file the changes:
https://github.com/lisps/tagfilter/blob/c1c2cfff483b9628765686037a4339249279434d/syntax/filter.php#L126-L130

**Comment by thisislukasbenz** [comment]
So I tried this on the Testing Wiki. I think it’s one step for ward now I get not an global error but just an error message. Here an image of it 

https://www.dropbox.com/s/nbp126k6qiob00u/IMG_4036.HEIC?dl=0

does this help you ? 
and to the one message all helper tagfilter plugins are installed so the second message I don’t know why it comes up.

**Comment by Klap-in** [comment]
The second message is caused by the first message. 

I see already the crulpit, I made a typo in my suggestion. I'm sorry! I see that proposing edits via the comments here is more sensitive for errors :-S

```diff
- 		return mb_convert_case(str_replace('_',' ',trim($label,':')), MB_CASE_TITLE, "UTF-8");
+		return dokuwiki\Utf8\PhpString::ucwords(str_replace('_',' ',trim($label,':')));
```
So change `;::` into `::` please.

If this does not work: In the first message there is told the error log contains more info. Could you then check the error log for this message and share it please?

**Comment by thisislukasbenz** [comment]
Dudeeeee thank you a tonnnnnn!!!!! All seems to Work now without any Problems tested already various functions of the Plugin and all seems to work without any Problems!!

**Comment by Klap-in** [comment]
Nice!
I will create an update for this plugin. If it is ready, could I ask you to test?

**Comment by thisislukasbenz** [comment]
Yes completely no problem I have the time! Whenever you made an update let me know and I will test it for you.

**Comment by Klap-in** [comment]
Hi @thisislukasbenz,

I made an update. You can got a _test_ version from: https://github.com/Klap-in/tagfilter/archive/refs/heads/master.zip
If I broke some thing unexpected, please share.

**Comment by thisislukasbenz** [comment]
I tested all out. Overall installed Wiki complete new and now without any Code changes with the new Test Update it works now. Only one Problem now the Sites that have Tags always gets shown in the List and i cant hide them, as i used it normaly Blank Page you choose a Tag and then the Pages with that Tag get shown. Now all sides that have Tags get shown even when no Tag is selected to be displayed... Thats the only Issue i have so far!

**Comment by thisislukasbenz** [comment]
I switched it again to open now only that Issue i try to remove and maybe you can give me also an Info on how to make it work then its fully closed...
