### ISSUE TITLE
collaboration tagfilter <-> include plugins?

### ISSUE THREAD

**Issue by fjf2002** [lisps/tagfilter#25]
I would be interested to combine features of the tagfilter and include plugins as follows:

* Embed the form of the tagfilter plugin
* Instead of listing the hyperlinks of the pages containing the tags, embed the pages themselves using the include plugin.

My plan would be,

1. Expose the include plugin's render function via a helper class,
2. Use it inside the tagfilter plugin. Refactoring is necessary.

Are you interested concerning your plugin? If so, I would elaborate deeper and make a pull request.

**Comment by fjf2002** [comment]
cf. https://github.com/dokufreaks/plugin-include/issues/294

**Comment by fjf2002** [comment]
Concerning the tagfilter plugin: As far as I understand, the full result list is loaded, and filtering is done on the browser side by means of setting filtered items 'display: none'. No communication to the server is done when filtering.

What is action.php's _ajax_call then good for? Is it dead code?

**Comment by peterfromearth** [comment]
you are right, I switched it to JS logic because we need an offline capable version. I forgot to remove the ajax method.

Feel free to create a pull request

**Comment by fjf2002** [comment]
Pull request if there, yet no reaction to date?
