### ISSUE TITLE
tagfilter-update 2023-10-09 seems buggy

### ISSUE THREAD

**Issue by virk** [lisps/tagfilter#29]
I updated the tagfilter-plugin to version 2023-10-09 and now tag-behavior has changed: While before updating
`{{tagfilter>?Projekt=project:.*|Art=art:.*|Detail=detail:.*|Jahr=year:.*&nouser&nodate&notags&noneonclear&multi&count}}`
only showed tags, when I selected some fields in the drop-down-menus (which I consider to be correct), now after the update always a list of all tagged pages is shown and tagfilter displays 221/221 found. (Seems there are in total 221 pages tagged somehow)
Somebody from dokuwiki-forum has already confirmed that behaviour and considers this a bug. Has anybody got an idea what might be wrong and how I could solve this?

**Comment by Klap-in** [comment]
I tried also a bit with the different commits. If I test with the code up to commit https://github.com/lisps/tagfilter/commit/7a26aa3823f58f383b8abf8cdede493788f62ede then the filter stops working. (Commits before works. Not tested follow up commits).

@fjf2002 could you have a look please?

**Comment by fjf2002** [comment]
Thanks for the report, I will check soon.

**Comment by fjf2002** [comment]
I am testing currently. The problem is dependent on your current plugin»pagelist»style setting. "standard" and "table/list" are broken, the other two work.

**Comment by virk** [comment]
I can somehow confirm, but here, only "simple list" work, the other three options show that broken behaviour.

**Comment by fjf2002** [comment]
See PR, please review and merge. Thank You. Sorry for introducing the bug in the first case.

**Comment by virk** [comment]
I tried to apply the code changes manually, but here that did not solve my problem. The changes which needed to be applied were only two (lines approx.18 and 105-120) in tagfilter/script.js, yes?

**Comment by Klap-in** [comment]
About caching: After a change of the javascript you have to reload your browser caches for the site as well. Best is to reload with Ctrl+F5 (in e.g. Chrome).
